<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Find finished quiz attempts whose wrong / unanswered questions never got a revision module
 * (e.g. blank answers before v1.3.0) and re-queue them. Dry run by default.
 *
 *   php local/aiquizremedial/cli/rescan.php --days=14
 *   php local/aiquizremedial/cli/rescan.php --days=14 --courseid=5 --execute
 *
 * Re-queued attempts are generated by the scheduled task and consume AI credits.
 *
 * @package    local_aiquizremedial
 * @copyright  2026 LMS-Labs
 * @license    http://www.gnu.org/licenses/gpl-3.0.html GNU GPL v3 or later
 */

define('CLI_SCRIPT', true);
require(__DIR__ . '/../../../config.php');
require_once($CFG->libdir . '/clilib.php');

[$options, $unrecognised] = cli_get_params(
    ['days' => 7, 'courseid' => 0, 'execute' => false, 'help' => false],
    ['h' => 'help']
);
if ($options['help'] || $unrecognised) {
    echo "Re-scan finished quiz attempts for wrong answers that have no revision module.

Options:
  --days=N        Look at attempts finished in the last N days (default 7)
  --courseid=N    Limit to one course
  --execute       Actually queue the attempts (default is a dry run)
  -h, --help      Show this help
";
    exit(0);
}

$since = time() - ((int) $options['days'] * DAYSECS);
$processor = new \local_aiquizremedial\job_processor(function (string $line) {
    cli_writeln($line);
});
[$checked, $reopened, $wrong] = $processor->rescan($since, (int) $options['courseid'], !$options['execute']);
cli_writeln("Attempts checked: {$checked}");
cli_writeln("Attempts with missing modules: {$reopened} ({$wrong} question(s))");
cli_writeln($options['execute']
    ? 'Queued. The scheduled task will generate the modules on its next run.'
    : 'Dry run only — re-run with --execute to queue them.');
